In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('spam.csv')
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [3]:
df.Category.value_counts()

Category
ham     4825
spam     747
Name: count, dtype: int64

In [4]:
# def get_spam_number(x):
#     if x == 'spam':
#         retrun 1
#     else:
#         return 0

# this is for cnverting text from number

In [5]:
df['spam'] = df['Category'].apply(lambda x: 1 if x == 'spam' else 0)

# it will create new column and we apply our transformation function that create text into number

In [6]:
df.shape

(5572, 3)

In [7]:
df.tail()

Category                                            Message  spam
5567     spam  This is the 2nd time we have tried 2 contact u...     1
5568      ham               Will ü b going to esplanade fr home?     0
5569      ham  Pity, * was in mood for that. So...any other s...     0
5570      ham  The guy did some bitching but I acted like i'd...     0
5571      ham                         Rofl. Its true to its name     0

In [8]:
df.head(10)

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0
5     spam  FreeMsg Hey there darling it's been 3 week's n...     1
6      ham  Even my brother is not like to speak with me. ...     0
7      ham  As per your request 'Melle Melle (Oru Minnamin...     0
8     spam  WINNER!! As a valued network customer you have...     1
9     spam  Had your mobile 11 months or more? U R entitle...     1

# Train test split

In [9]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df.Message, df.spam, test_size=0.2)

In [10]:
X_train.shape

(4457,)

In [11]:
X_test.shape

(1115,)

In [12]:
type(X_train)

pandas.core.series.Series

In [13]:
X_train[:4]

2609                            Hello madam how are you ?
3624                Damn, poor zac doesn't stand a chance
1434    You intrepid duo you! Have a great time and se...
1980                   Shhhhh nobody is supposed to know!
Name: Message, dtype: object

In [15]:
#X_train[:4][152]

# To check any particular email

In [16]:
type(y_train)


pandas.core.series.Series

In [17]:
y_train[:4]

# i want to check first 4 samples

2609    0
3624    0
1434    0
1980    0
Name: spam, dtype: int64

In [18]:
type(X_train.values)

numpy.ndarray

# Create bag of words representation using CountVectorizer

In [19]:
X_train.values

array(['Hello madam how are you ?',
       "Damn, poor zac doesn't stand a chance",
       'You intrepid duo you! Have a great time and see you both soon.',
       ...,
       'Natalja (25/F) is inviting you to be her friend. Reply YES-440 or NO-440 See her: www.SMS.ac/u/nat27081980 STOP? Send STOP FRND to 62468',
       'Prepare to be pounded every night...',
       'Two fundamentals of cool life: "Walk, like you are the KING"...! OR "Walk like you Dont care,whoever is the KING"!... Gud nyt'],
      dtype=object)

In [20]:
from sklearn.feature_extraction.text import CountVectorizer

v = CountVectorizer() # class

X_train_CV = v.fit_transform(X_train.values)  # class has method called transform and apply on x_train to make bag of words
X_train_CV

# it will create vocabulary and then count the occurence of word

<4457x7678 sparse matrix of type '<class 'numpy.int64'>'
	with 59094 stored elements in Compressed Sparse Row format>

In [21]:
X_train_CV.toarray() # converting it to array(sparse vector to numpy array)

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [22]:
X_train_CV.toarray()[:2] # To look first 2 samples

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [23]:
X_train_CV.toarray()[:2][0] #first sample

array([0, 0, 0, ..., 0, 0, 0])

In [24]:
X_train_CV.shape

(4457, 7678)

In [25]:
v.get_feature_names_out()   

# for printing the whole vocab we use the variable v that we put variable for count vectorizer.
# if we do v.get_features_names_out it will give our whole vocab

array(['00', '000', '000pes', ..., 'èn', 'ú1', '〨ud'], dtype=object)

In [26]:
v.get_feature_names_out()[1771] #specific word

'chex'

In [27]:
v.vocabulary_  # it will give the position of word in vocab

{'hello': 3382,
 'madam': 4264,
 'how': 3497,
 'are': 1046,
 'you': 7636,
 'damn': 2152,
 'poor': 5247,
 'zac': 7662,
 'doesn': 2388,
 'stand': 6367,
 'chance': 1722,
 'intrepid': 3685,
 'duo': 2495,
 'have': 3340,
 'great': 3221,
 'time': 6831,
 'and': 953,
 'see': 5911,
 'both': 1444,
 'soon': 6247,
 'shhhhh': 6013,
 'nobody': 4745,
 'is': 3712,
 'supposed': 6548,
 'to': 6864,
 'know': 3921,
 'thanks': 6735,
 'for': 2931,
 'your': 7641,
 'message': 4416,
 'really': 5542,
 'appreciate': 1026,
 'sacrifice': 5800,
 'not': 4774,
 'sure': 6552,
 'of': 4834,
 'the': 6745,
 'process': 5375,
 'direct': 2332,
 'pay': 5064,
 'but': 1578,
 'will': 7446,
 'find': 2841,
 'out': 4954,
 'on': 4878,
 'my': 4619,
 'way': 7346,
 'back': 1191,
 'from': 3009,
 'test': 6712,
 'tomorrow': 6889,
 'in': 3611,
 'class': 1827,
 'now': 4786,
 'do': 2376,
 'wonderful': 7508,
 'day': 2180,
 'dunno': 2494,
 'dat': 2171,
 'wat': 7332,
 'he': 3350,
 'told': 6880,
 'me': 4365,
 'ok': 4859,
 'lor': 4168,
 'all': 903,

In [28]:
v.get_feature_names_out().shape

(7678,)

In [29]:
dir(v)  # to get all the methods

['__annotations__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__sklearn_clone__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_build_request_for_signature',
 '_char_ngrams',
 '_char_wb_ngrams',
 '_check_feature_names',
 '_check_n_features',
 '_check_stop_words_consistency',
 '_check_vocabulary',
 '_count_vocab',
 '_doc_link_module',
 '_doc_link_template',
 '_doc_link_url_param_generator',
 '_get_default_requests',
 '_get_doc_link',
 '_get_metadata_request',
 '_get_param_names',
 '_get_tags',
 '_limit_features',
 '_more_tags',
 '_parameter_constraints',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_sort_features',
 '_stop_words_id',
 '_validate_data',
 '_

In [30]:
X_train_np = X_train_CV.toarray()
X_train_np[0]

# this is my first email

array([0, 0, 0, ..., 0, 0, 0])

In [31]:
np.where(X_train_np[0]!=0)

# checking in first email where there is not zero

(array([1046, 3382, 3497, 4264, 7636]),)

In [33]:
# X_train[:4][152]

In [34]:
X_train

2609                            Hello madam how are you ?
3624                Damn, poor zac doesn't stand a chance
1434    You intrepid duo you! Have a great time and se...
1980                   Shhhhh nobody is supposed to know!
3970    Thanks for your message. I really appreciate y...
                              ...                        
3025    I love ya too but try and budget your money be...
4037                              How are you holding up?
5214    Natalja (25/F) is inviting you to be her frien...
3532                 Prepare to be pounded every night...
3508    Two fundamentals of cool life: "Walk, like you...
Name: Message, Length: 4457, dtype: object

In [35]:
X_train[4346]

'Enjoy urself tmr...'

In [36]:
X_train_np[0][1771]


np.int64(0)

# Train the naive bayes model

In [37]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(X_train_CV, y_train)


MultinomialNB()

In a Jupyter environment, please rerun this cell to show the HTML representation or trust the notebook.
On GitHub, the HTML representation is unable to render, please try loading this page with nbviewer.org.

In [38]:
X_test_CV = v.transform(X_test)

# Evaluate Performance

In [39]:
from sklearn.metrics import classification_report

y_pred = model.predict(X_test_CV)

print(classification_report(y_test, y_pred))

# when class is imbalanced then we use classification_report

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       966
           1       0.96      0.96      0.96       149

    accuracy                           0.99      1115
   macro avg       0.98      0.98      0.98      1115
weighted avg       0.99      0.99      0.99      1115



In [40]:
emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]

emails_count = v.transform(emails)
model.predict(emails_count)

array([0, 1])

# Train the model using sklearn pipeline and reduce number of lines of code

In [41]:
from sklearn.pipeline import Pipeline

clf = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('nb', MultinomialNB())
])

In [42]:
clf.fit(X_train, y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [43]:
y_pred = clf.predict(X_test)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       966
           1       0.96      0.96      0.96       149

    accuracy                           0.99      1115
   macro avg       0.98      0.98      0.98      1115
weighted avg       0.99      0.99      0.99      1115



# Assginment


    In this Exercise, you are going to classify whether a given movie review is positive or negative.
    you are going to use Bag of words for pre-processing the text and apply different classification algorithms.
    Sklearn CountVectorizer has the inbuilt implementations for Bag of Words.


In [44]:

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.ensemble import RandomForestClassifier
from  sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import Pipeline
from sklearn.metrics import classification_report


In [45]:
#1. read the data provided in the same directory with name 'movies_sentiment_data.csv' and store it in df variable
df = pd.read_csv("movies_sentiment_data.csv")


#2. print the shape of the data
print(df.shape)

#3. print top 5 datapoints
df.head()


(19000, 2)


review sentiment
0  I first saw Jake Gyllenhaal in Jarhead (2005) ...  positive
1  I enjoyed the movie and the story immensely! I...  positive
2  I had a hard time sitting through this. Every ...  negative
3  It's hard to imagine that anyone could find th...  negative
4  This is one military drama I like a lot! Tom B...  positive

In [46]:
#creating a new column "Category" which represent 1 if the sentiment is positive or 0 if it is negative
df['Category'] = df['sentiment'].apply(lambda x: 1 if x =='positive' else 0)


In [47]:
#check the distribution of 'Category' and see whether the Target labels are balanced or not.

df['Category'].value_counts()

Category
1    9500
0    9500
Name: count, dtype: int64

In [48]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df.review, df.Category, test_size=0.2)



Exercise-1

    using sklearn pipeline module create a classification pipeline to classify the movie review's positive or negative.

Note:

    use CountVectorizer for pre-processing the text.

    use Random Forest as the classifier with estimators as 50 and criterion as entropy.

    print the classification report.

References:

    https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestClassifier.html

    https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.CountVectorizer.html



In [49]:
#1. create a pipeline object
clf = Pipeline([
    ('vectorizer', CountVectorizer()),                                                    #initializing the vectorizer
    ('random_forest', (RandomForestClassifier(n_estimators=50, criterion='entropy')))      #using the RandomForest classifier
])



#2. fit with X_train and y_train
clf.fit(X_train, y_train)


#3. get the predictions for X_test and store it in y_pred
y_pred = clf.predict(X_test)


#4. print the classfication report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.84      0.83      0.83      1963
           1       0.82      0.83      0.82      1837

    accuracy                           0.83      3800
   macro avg       0.83      0.83      0.83      3800
weighted avg       0.83      0.83      0.83      3800





    As you can see above, for both the classes (positive and negative sentiment) we got more than 80% precision, recall and f1- score. This seems to be an acceptable performance.

Exercise-2

    using sklearn pipeline module create a classification pipeline to classify the movie review's positive or negative..

Note:

    use CountVectorizer for pre-processing the text.
    use KNN as the classifier with n_neighbors of 10 and metric as 'euclidean'.
    print the classification report.


In [ ]:
#1. create a pipeline object
clf = Pipeline([
                
     ('vectorizer', CountVectorizer()),   
      ('KNN', (KNeighborsClassifier(n_neighbors=10, metric = 'euclidean')))   #using the KNN classifier with 10 neighbors 
])


#2. fit with X_train and y_train
clf.fit(X_train, y_train)


#3. get the predictions for X_test and store it in y_pred
y_pred = clf.predict(X_test)


#4. print the classfication report
print(classification_report(y_test, y_pred))

Exercise-3

    using sklearn pipeline module create a classification pipeline to classify the movie review's positive or negative..

Note:

    use CountVectorizer for pre-processing the text.
    use Multinomial Naive Bayes as the classifier.
    print the classification report.


In [ ]:
#1. create a pipeline object
clf = Pipeline([
                
     ('vectorizer', CountVectorizer()),   
      ('Multi NB', MultinomialNB())   #using the Multinomial Naive Bayes classifier 
])


#2. fit with X_train and y_train
clf.fit(X_train, y_train)


#3. get the predictions for X_test and store it in y_pred
y_pred = clf.predict(X_test)


#4. print the classfication report
print(classification_report(y_test, y_pred))


Can you write some observations of why model like KNN fails to produce good results unlike RandomForest and MultinomialNB?

    As Machine learning algorithms does not work on Text data directly, we need to convert them into numeric vector and feed that into models while training.
    In this process, we convert text into a very high dimensional numeric vector using the technique of Bag of words.
    Model like K-Nearest Neighbours(KNN) doesn't work well with high dimensional data because with large number of dimensions, it becomes difficult for the algorithm to calculate distance in each dimension. In higher dimensional space, the cost to calculate distance becomes expensive and hence impacts the performance of model.
    The easy calculation of probabilities for the words in corpus(Bag of words) and storing them in contigency table is the major reason for the Multinomial NaiveBayes to be a text classification friendly algorithm.
    As Random Forest uses Bootstrapping(Row and column Sampling) with many decision tree and overcomes the high variance and overfitting of high dimensional data and also uses feature importance of words for better classifing the categories.
    Machine Learning is like trial and error scientific method, where we keep trying all the possible algorithms we have and select the one which give good results and satisfy the requirements like latency, interpretability etc.

Refer these resources to get good idea:

    https://stackabuse.com/k-nearest-neighbors-algorithm-in-python-and-scikit-learn/
    https://analyticsindiamag.com/naive-bayes-why-is-it-favoured-for-text-related-tasks/

